[versions]
androidx-core = "1.13.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.1.4"
androidx-fragment = "1.8.3"
androidx-lifecycle = "2.8.4"
androidx-recyclerview = "1.3.2"
espresso-core = "3.7.0"
junit = "1.3.0"
material = "1.12.0"
coil = "2.6.0"
media = "1.7.1"
media3 = "1.4.1"
media3-exoplayer = "1.8.0"
media3-session = "1.8.0"
media3-ui = "1.8.0"
room = "2.6.1"
agp = "8.4.0"
kotlin = "1.9.24"
rules = "1.6.0-alpha01"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-media3-exoplayer-v180 = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
androidx-media3-session-v180 = { module = "androidx.media3:media3-session", version.ref = "media3-session" }
androidx-media3-ui-v180 = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }
media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

